name: Hourly HVO Volcano Status Update

on:
  schedule:
    - cron: "0 * * * *"  # every hour UTC
  workflow_dispatch:

jobs:
  update-hvo-hourly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run hourly HVO ingestion
        run: |
          python src/ingestion/hvo.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: hvo-status-hourly
          path: data/raw/hvo/hvo_status.csv
